CREATE TABLE Evaluation
(
  EvID INT NOT NULL,
  Grade INT NOT NULL,
  Year INT NOT NULL,
  EmID INT NOT NULL,
  PRIMARY KEY (EvID),
  FOREIGN KEY (EmID) REFERENCES Employee(EmID)
);

CREATE TABLE Computer
(
  CID INT NOT NULL,
  Processor VARCHAR(5) NOT NULL,
  RAM INT NOT NULL,
  SSD INT NOT NULL,
  YearOfPurchase INT NOT NULL,
  PRIMARY KEY (CID)
);

CREATE TABLE Supplier
(
  SuID INT NOT NULL,
  SuName VARCHAR(50) NOT NULL,
  Addres VARCHAR(50) NOT NULL,
  SuPhone VARCHAR(15) NOT NULL,
  SuEmail VARCHAR(50) NOT NULL,
  PRIMARY KEY (SuID)
);

CREATE TABLE Room
(
  RoomNumber INT NOT NULL,
  Space INT NOT NULL,
  Floor INT NOT NULL,
  PRIMARY KEY (RoomNumber)
);

CREATE TABLE Team
(
  TeID INT NOT NULL,
  TeName VARCHAR(50) NOT NULL,
  RoomNumber INT NOT NULL,
  PRIMARY KEY (TeID),
  FOREIGN KEY (RoomNumber) REFERENCES Room(RoomNumber)
);

CREATE TABLE Project
(
  ProID INT NOT NULL,
  ProName VARCHAR(50) NOT NULL,
  DueDate DATE NOT NULL,
  Cost INT NOT NULL,
  Profit INT NOT NULL,
  TeID INT NOT NULL,
  PRIMARY KEY (ProID),
  FOREIGN KEY (TeID) REFERENCES Team(TeID)
);

CREATE TABLE Printer
(
  PriID INT NOT NULL,
  Compeny VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  SuID INT NOT NULL,
  PRIMARY KEY (PriID),
  FOREIGN KEY (SuID) REFERENCES Supplier(SuID)
);

CREATE TABLE Software
(
  SoId INT NOT NULL,
  SoName VARCHAR(50) NOT NULL,
  Version VARCHAR(10) NOT NULL,
  SuID INT NOT NULL,
  PRIMARY KEY (SoId),
  FOREIGN KEY (SuID) REFERENCES Supplier(SuID)
);

CREATE TABLE ConnectedTo
(
  PriID INT NOT NULL,
  CID INT NOT NULL,
  PRIMARY KEY (PriID, CID),
  FOREIGN KEY (PriID) REFERENCES Printer(PriID),
  FOREIGN KEY (CID) REFERENCES Computer(CID)
);

CREATE TABLE InstalledOn
(
  CID INT NOT NULL,
  SoId INT NOT NULL,
  PRIMARY KEY (CID, SoId),
  FOREIGN KEY (CID) REFERENCES Computer(CID),
  FOREIGN KEY (SoId) REFERENCES Software(SoId)
);

CREATE TABLE Employee
(
  EmID INT NOT NULL,
  EmName VARCHAR(50) NOT NULL,
  DateOfBirth DATE NOT NULL,
  RoleID INT NOT NULL,
  TeID INT NOT NULL,
  CID INT NOT NULL,
  PRIMARY KEY (EmID),
  FOREIGN KEY (RoleID) REFERENCES Role(RoleID),
  FOREIGN KEY (TeID) REFERENCES Team(TeID),
  FOREIGN KEY (CID) REFERENCES Computer(CID)
);

CREATE TABLE Role
(
  RoleID INT NOT NULL,
  RoleName VARCHAR(50) NOT NULL,
  PRIMARY KEY (RoleID)
);
